cacheFolder: "D:\\Tools\\yarn\\cache"

compressionLevel: mixed

enableGlobalCache: false

globalFolder: "D:\\Tools\\yarn\\global"

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/echo-execute"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
