#!/usr/bin/env bash
set -e

#
# Helpers
##################################################

export PATH="$PATH:node_modules/.bin"
export ROOT="$PWD"

source bash-partials/colors.sh
source bash-partials/env.sh

function run() {
  echo "$@"
  "$@"
}

#
# Commands
##################################################

function build() {
  run rm -rf dist/*.sh
  run rm -rf build

  run mkdir -p dist
  run mkdir -p build/bash
  run mkdir -p build/bash-partials

  run tsc -p tsconfig.json
  run node build/bash/generate.js

  run cp build/bash/index.sh dist/bash.sh

  # preserve existing package.json
  if [ ! -f dist/package.json ]; then
    echo '{"name":"dotfiles","version":"1.0.0","private":true}' > dist/package.json
  fi
}

function update() {
  build

  run cd "$ROOT/dist"
  run source bash.sh
  run pnpm update --latest
}

#
# CLI
##################################################

#
# Call the function specified by the first parameter, passing all remaining
# parameters to the function. If no such function exists, display usage info.
#
if [ -n "$1" ] && type $1 | grep -i function > /dev/null; then
  pnpm i
  command="$1"
  shift
  $command ${@}
else
  fail "No such command: $1"
fi
