#!/usr/bin/env bash
set -euo pipefail

UBUNTU="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON="$(cd "$UBUNTU/../common" && pwd)"

# Comment out a line to skip that tool. Uncomment to include it.

source "$UBUNTU/os.sh"
source "$COMMON/hushlogin.sh"
source "$UBUNTU/network.sh"
source "$UBUNTU/apt.sh"
source "$UBUNTU/brew.sh"
source "$UBUNTU/git.sh"
source "$UBUNTU/gum.sh"
source "$UBUNTU/gh.sh"
source "$UBUNTU/glab.sh"
source "$UBUNTU/acli.sh"
source "$COMMON/copilot.sh"
source "$COMMON/claude.sh"
source "$COMMON/grok.sh"
source "$COMMON/cursor.sh"
source "$COMMON/codex.sh"
source "$UBUNTU/dotfiles.sh"
source "$UBUNTU/nvm.sh"
source "$UBUNTU/node.sh"
source "$UBUNTU/npm.sh"
source "$UBUNTU/bun.sh"
source "$COMMON/config.sh"
source "$COMMON/heroku.sh"
source "$UBUNTU/aws.sh"
source "$UBUNTU/gcloud.sh"
source "$UBUNTU/kubectl.sh"
source "$UBUNTU/kustomize.sh"
source "$UBUNTU/docker.sh"
source "$UBUNTU/php.sh"
source "$COMMON/composer.sh"
source "$COMMON/wp-cli.sh"
source "$UBUNTU/rust.sh"
source "$UBUNTU/ast-grep.sh"
source "$UBUNTU/killport.sh"
source "$UBUNTU/go.sh"
source "$COMMON/plow.sh"
source "$UBUNTU/deno.sh"
source "$UBUNTU/fly.sh"
source "$COMMON/sst.sh"
source "$COMMON/kimi.sh"
source "$UBUNTU/cloudflared.sh"
source "$UBUNTU/sentry-cli.sh"
source "$UBUNTU/op.sh"

# source "$UBUNTU/doctl.sh"
# source "$UBUNTU/railway.sh"
