#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Comment out a line to skip that tool. Uncomment to include it.

source "$DIR/os.sh"
source "$DIR/hushlogin.sh"
source "$DIR/network.sh"
source "$DIR/apt.sh"
source "$DIR/brew.sh"
source "$DIR/git.sh"
source "$DIR/gum.sh"
source "$DIR/gh.sh"
source "$DIR/glab.sh"
source "$DIR/copilot.sh"
source "$DIR/claude.sh"
source "$DIR/grok.sh"
source "$DIR/cursor.sh"
source "$DIR/codex.sh"
source "$DIR/dotfiles.sh"
source "$DIR/nvm.sh"
source "$DIR/node.sh"
source "$DIR/npm.sh"
source "$DIR/bun.sh"
source "$DIR/config.sh"
source "$DIR/heroku.sh"
source "$DIR/aws.sh"
source "$DIR/gcloud.sh"
source "$DIR/kubectl.sh"
source "$DIR/kustomize.sh"
source "$DIR/docker.sh"
source "$DIR/php.sh"
source "$DIR/composer.sh"
source "$DIR/wp-cli.sh"
source "$DIR/rust.sh"
source "$DIR/ast-grep.sh"
source "$DIR/killport.sh"
source "$DIR/zsh.sh"
source "$DIR/go.sh"
source "$DIR/plow.sh"

# source "$DIR/doctl.sh"
# source "$DIR/op.sh"
# source "$DIR/railway.sh"
