version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run: yarn install --frozen-lockfile --no-progress
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  update:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - dist-yarn-cache-{{ checksum "dist/yarn.lock" }}
            - dist-yarn-cache-
      - run: ./dot update
      - save_cache:
          key: dist-yarn-cache-{{ checksum "dist/yarn.lock" }}
          paths: dist/node_modules

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: ./dot lint

workflows:
  version: 2
  default:
    jobs:
      - install
      - update:
          requires:
            - install
      - lint:
          requires:
            - install
