#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON="$(cd "$DIR/../common" && pwd)"
source "$DIR/_lib.sh"

# Comment out a line to skip that tool. Uncomment to include it.

source "$DIR/os.sh"
source "$COMMON/hushlogin.sh"
source "$DIR/pkg.sh"
source "$DIR/brew.sh"
source "$DIR/git.sh"
source "$DIR/gum.sh"
source "$DIR/gh.sh"
source "$DIR/glab.sh"
source "$DIR/acli.sh"
# copilot/claude/grok/cursor/codex come from Omarchy mise
# source "$COMMON/copilot.sh"
# source "$COMMON/claude.sh"
# source "$COMMON/grok.sh"
# source "$COMMON/cursor.sh"
# source "$COMMON/codex.sh"
source "$DIR/dotfiles.sh"
source "$DIR/node.sh"
source "$COMMON/npm.sh"
source "$DIR/bun.sh"
source "$COMMON/config.sh"
source "$COMMON/heroku.sh"
source "$DIR/aws.sh"
source "$DIR/gcloud.sh"
source "$DIR/kubectl.sh"
source "$DIR/kustomize.sh"
source "$DIR/docker.sh"
source "$DIR/php.sh"
source "$COMMON/wp-cli.sh"
source "$DIR/rust.sh"
source "$DIR/ast-grep.sh"
source "$DIR/killport.sh"
source "$DIR/go.sh"
source "$COMMON/plow.sh"
source "$DIR/deno.sh"
source "$DIR/fly.sh"
source "$COMMON/sst.sh"
source "$COMMON/kimi.sh"
source "$DIR/cloudflared.sh"
source "$DIR/sentry-cli.sh"
source "$DIR/op.sh"
