export const key = {
  any: "any",

  alt: "alt",
  arrow: "arrow",
  backspace: "delete_or_backspace",
  command: "command",
  control: "control",
  delete_forward: "delete_forward",
  delete: "delete_or_backspace",
  end: "end",
  enter: "return_or_enter",
  escape: "escape",
  fn: "fn",
  home: "home",
  insert: "insert",
  option: "option",
  print_screen: "print_screen",
  return: "return_or_enter",
  shift: "shift",
  spacebar: "spacebar",
  tab: "tab",
  win: "win",

  left_alt: "left_alt",
  left_command: "left_command",
  left_control: "left_control",
  left_option: "left_option",
  left_shift: "left_shift",
  left_win: "left_win",

  right_alt: "right_alt",
  right_command: "right_command",
  right_control: "right_control",
  right_option: "right_option",
  right_shift: "right_shift",
  right_win: "right_win",

  arrow_down: "down_arrow",
  arrow_left: "left_arrow",
  arrow_right: "right_arrow",
  arrow_up: "up_arrow",

  f1: "f1",
  f2: "f2",
  f3: "f3",
  f4: "f4",
  f5: "f5",
  f6: "f6",
  f7: "f7",
  f8: "f8",
  f9: "f9",
  f0: "f0",

  number1: "1",
  number2: "2",
  number3: "3",
  number4: "4",
  number5: "5",
  number6: "6",
  number7: "7",
  number8: "8",
  number9: "9",
  number0: "0",

  a: "a",
  b: "b",
  c: "c",
  d: "d",
  e: "e",
  f: "f",
  g: "g",
  h: "h",
  i: "i",
  j: "j",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  o: "o",
  p: "p",
  q: "q",
  r: "r",
  s: "s",
  t: "t",
  u: "u",
  v: "v",
  w: "w",
  x: "x",
  y: "y",
  z: "z",
} as const
